version: "3.9"

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=measurements
      - DB_PORT=5432
    networks:
      - envirotrack_Enviro-network

networks:
  envirotrack_Enviro-network:
    external: true
